version: '2'

volumes:
    database_data:
        driver: local

services:
###########################
# Setup the Nginx container
###########################
    nginx:
        image: nginx:latest
        ports:
            - 8080:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - php

###########################
# Setup the PHP container
###########################
    php:
        build: ./docker/php/
        volumes:
            - .:/var/www/html

###########################
# Setup the Database (MySQL) container
###########################
    mysql:
        image: mysql:latest
        volumes:
            - ./other_files:/usr/local/data
            - database_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: leap
            MYSQL_USER: leap  
            MYSQL_PASSWORD: password
